using System.Data.Common;
using Druse.Database.Abstractions;
using Druse.Domain;

namespace Druse.Provider.PostgreSql;

/// <summary>DDL de PostgreSQL. Solo aporta su dialecto.</summary>
public sealed class PostgreSqlTableDesigner : TableDesignerBase
{
    public override DatabaseEngine Engine => DatabaseEngine.PostgreSql;

    public override IReadOnlyList<string> CommonDataTypes =>
    [
        "integer", "bigint", "smallint", "boolean",
        "numeric(18,2)", "real", "double precision",
        "text", "varchar(50)", "varchar(255)", "char(10)",
        "date", "timestamp", "timestamptz", "time", "interval",
        "uuid", "json", "jsonb", "bytea",
    ];

    /// <summary>
    /// PostgreSQL tiene un tipo para casi todo, así que casi nada se pierde al
    /// llegar aquí: identificadores únicos, JSON y textos sin límite son tipos
    /// propios y no apaños sobre texto.
    /// </summary>
    public override string TypeFor(TypeFacets facets) => facets.Family switch
    {
        ColumnFamily.Uuid => "uuid",
        ColumnFamily.Boolean => "boolean",
        ColumnFamily.Integral => "bigint",
        ColumnFamily.Fractional => facets.Precision is { } precision
            ? $"numeric({precision},{facets.Scale ?? 0})"
            : "double precision",
        ColumnFamily.Date => "date",
        ColumnFamily.Time => "time",
        ColumnFamily.Timestamp => "timestamp",
        ColumnFamily.TimestampWithZone => "timestamptz",
        ColumnFamily.Binary => "bytea",
        _ when facets.IsJson => "jsonb",
        _ when facets.IsUnbounded || facets.Length is null => "text",
        _ => $"varchar({facets.Length})",
    };

    /// <summary>
    /// PostgreSQL es el más completo de los tres en índices: admite columnas
    /// incluidas desde la 11, índices parciales desde siempre y varias
    /// estructuras. `hash` y `brin` se ofrecen porque tienen usos claros, no por
    /// listar todo lo que existe.
    /// </summary>
    public override IndexCapabilities IndexCapabilities => new()
    {
        SupportsIncludedColumns = true,
        SupportsFilter = true,
        SupportsSortDirection = true,
        Methods = ["btree", "hash", "gin", "gist", "brin"],
    };

    /// <summary>
    /// `bytea` se escribe con su forma hexadecimal entre comillas, no con `0x`.
    ///
    /// Depende de que la conexión trate la barra invertida como un carácter más
    /// —`standard_conforming_strings`, encendido desde PostgreSQL 9.1 y lo que
    /// pone Npgsql—; con la opción apagada haría falta duplicarla.
    /// </summary>
    protected override string BinaryLiteral(byte[] value)
    {
        ArgumentNullException.ThrowIfNull(value);

        return $"'\\x{Convert.ToHexString(value).ToLowerInvariant()}'";
    }

    /// <summary>Comillas dobles, duplicándolas para que no se pueda escapar.</summary>
    protected override string Quote(string identifier) =>
        $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";

    /// <summary>
    /// `IF NOT EXISTS` y no un `CREATE SCHEMA` a secas: el respaldo tiene que
    /// poder aplicarse tanto sobre una base recién creada como sobre una donde el
    /// esquema ya está, y fallar en la primera línea del segundo caso sería peor
    /// que no escribirlo.
    /// </summary>
    public override IReadOnlyList<string> ScriptSchema(string schema) =>
        string.IsNullOrWhiteSpace(schema) ? [] : [$"CREATE SCHEMA IF NOT EXISTS {Quote(schema)};"];

    /// <summary>El mismo normalizador que usan las consultas de este motor.</summary>
    protected override QueryError Normalize(Exception exception) =>
        PostgreSqlErrorNormalizer.Normalize(exception);

    protected override DbConnection Connection(IDatabaseSession session) =>
        session is PostgreSqlSession postgres
            ? postgres.Connection
            : throw new ArgumentException(
                "La sesión no pertenece al proveedor PostgreSQL.",
                nameof(session));

    /// <summary>
    /// `GENERATED BY DEFAULT AS IDENTITY` en lugar de `serial`.
    ///
    /// Es el estándar desde PostgreSQL 10 y no crea una secuencia suelta que
    /// sobreviva a la tabla, como sí hacía `serial`.
    /// </summary>
    protected override string IdentityClause(TableColumnDefinition column) =>
        "GENERATED BY DEFAULT AS IDENTITY";

    /// <summary>
    /// PostgreSQL parte cada cambio en su propia acción.
    ///
    /// Cambiar el tipo puede necesitar una conversión explícita; se escribe el
    /// `USING` solo cuando hace falta, y como aquí no se sabe, se deja que el
    /// motor decida y falle con su propio mensaje, que es claro.
    /// </summary>
    protected override IReadOnlyList<string> AlterColumn(
        string qualifiedTable,
        ColumnAlteration change)
    {
        var statements = new List<string>();
        var column = change.Column;

        if (change.IsRename)
        {
            statements.Add(
                $"ALTER TABLE {qualifiedTable} RENAME COLUMN " +
                $"{Quote(change.CurrentName)} TO {Quote(column.Name)};");
        }

        var name = Quote(column.Name);

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} TYPE {column.DataType.Trim()};");

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} " +
            (column.IsNullable ? "DROP NOT NULL;" : "SET NOT NULL;"));

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} " +
            (string.IsNullOrWhiteSpace(column.DefaultValue)
                ? "DROP DEFAULT;"
                : $"SET DEFAULT {column.DefaultValue.Trim()};"));

        return statements;
    }

    protected override string RenameTable(
        string qualifiedTable,
        DatabaseObject table,
        string newName) =>
        $"ALTER TABLE {qualifiedTable} RENAME TO {Quote(newName)};";

    /// <summary>
    /// Aquí un índice es un objeto del esquema, no algo colgado de la tabla.
    ///
    /// Por eso se borra por su nombre calificado y sin mencionar la tabla, que es
    /// justo al revés que en SQL Server y MySQL.
    /// </summary>
    protected override string DropIndex(
        string qualifiedTable,
        DatabaseObject table,
        string indexName)
    {
        ArgumentNullException.ThrowIfNull(table);

        return $"DROP INDEX {Qualify(table.Database, table.Schema, indexName)};";
    }
}
