using System.Data.Common;
using Druse.Database.Abstractions;
using Druse.Domain;

namespace Druse.Provider.PostgreSql;

/// <summary>DDL de PostgreSQL. Solo aporta su dialecto.</summary>
public sealed class PostgreSqlTableDesigner : TableDesignerBase
{
    public override DatabaseEngine Engine => DatabaseEngine.PostgreSql;

    public override IReadOnlyList<string> CommonDataTypes =>
    [
        "integer", "bigint", "smallint", "boolean",
        "numeric(18,2)", "real", "double precision",
        "text", "varchar(50)", "varchar(255)", "char(10)",
        "date", "timestamp", "timestamptz", "time", "interval",
        "uuid", "json", "jsonb", "bytea",
    ];

    /// <summary>Comillas dobles, duplicándolas para que no se pueda escapar.</summary>
    protected override string Quote(string identifier) =>
        $"\"{identifier.Replace("\"", "\"\"", StringComparison.Ordinal)}\"";

    protected override DbConnection Connection(IDatabaseSession session) =>
        session is PostgreSqlSession postgres
            ? postgres.Connection
            : throw new ArgumentException(
                "La sesión no pertenece al proveedor PostgreSQL.",
                nameof(session));

    /// <summary>
    /// `GENERATED BY DEFAULT AS IDENTITY` en lugar de `serial`.
    ///
    /// Es el estándar desde PostgreSQL 10 y no crea una secuencia suelta que
    /// sobreviva a la tabla, como sí hacía `serial`.
    /// </summary>
    protected override string IdentityClause(TableColumnDefinition column) =>
        "GENERATED BY DEFAULT AS IDENTITY";

    /// <summary>
    /// PostgreSQL parte cada cambio en su propia acción.
    ///
    /// Cambiar el tipo puede necesitar una conversión explícita; se escribe el
    /// `USING` solo cuando hace falta, y como aquí no se sabe, se deja que el
    /// motor decida y falle con su propio mensaje, que es claro.
    /// </summary>
    protected override IReadOnlyList<string> AlterColumn(
        string qualifiedTable,
        ColumnAlteration change)
    {
        var statements = new List<string>();
        var column = change.Column;

        if (change.IsRename)
        {
            statements.Add(
                $"ALTER TABLE {qualifiedTable} RENAME COLUMN " +
                $"{Quote(change.CurrentName)} TO {Quote(column.Name)};");
        }

        var name = Quote(column.Name);

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} TYPE {column.DataType.Trim()};");

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} " +
            (column.IsNullable ? "DROP NOT NULL;" : "SET NOT NULL;"));

        statements.Add(
            $"ALTER TABLE {qualifiedTable} ALTER COLUMN {name} " +
            (string.IsNullOrWhiteSpace(column.DefaultValue)
                ? "DROP DEFAULT;"
                : $"SET DEFAULT {column.DefaultValue.Trim()};"));

        return statements;
    }

    protected override string RenameTable(
        string qualifiedTable,
        DatabaseObject table,
        string newName) =>
        $"ALTER TABLE {qualifiedTable} RENAME TO {Quote(newName)};";
}
