import { DatabaseEngine } from '../../../shared/models/workspace';
import { functionReferences } from './sql-reference';

/**
 * Palabras reservadas comunes a los motores soportados.
 *
 * La lista es corta a propósito: sugerir cientos de palabras convierte el
 * autocompletado en ruido y estorba más que ayuda. Están las que se escriben a
 * diario.
 */
const COMMON_KEYWORDS: readonly string[] = [
  'SELECT',
  'FROM',
  'WHERE',
  'GROUP BY',
  'HAVING',
  'ORDER BY',
  'LIMIT',
  'INSERT INTO',
  'VALUES',
  'UPDATE',
  'SET',
  'DELETE FROM',
  'INNER JOIN',
  'LEFT JOIN',
  'RIGHT JOIN',
  'FULL JOIN',
  'CROSS JOIN',
  'ON',
  'AND',
  'OR',
  'NOT',
  'IN',
  'EXISTS',
  'BETWEEN',
  'LIKE',
  'IS NULL',
  'IS NOT NULL',
  'AS',
  'DISTINCT',
  'CASE',
  'WHEN',
  'THEN',
  'ELSE',
  'END',
  'WITH',
  'UNION',
  'UNION ALL',
  'INTERSECT',
  'EXCEPT',
  'CREATE TABLE',
  'ALTER TABLE',
  'DROP TABLE',
  'TRUNCATE TABLE',
  'CREATE INDEX',
  'CREATE VIEW',
  'PRIMARY KEY',
  'FOREIGN KEY',
  'REFERENCES',
  'BEGIN',
  'COMMIT',
  'ROLLBACK',
  'ASC',
  'DESC',
  'NULL',
  'TRUE',
  'FALSE',
];

/**
 * Palabras propias de Informix. Las comparten sus dos motores: cambia el
 * transporte, no el dialecto.
 */
const INFORMIX_KEYWORDS = [
  // `FIRST` y `SKIP` son lo propio de Informix y lo que peor se recuerda:
  // van después del SELECT, no al final como `LIMIT`.
  'FIRST',
  'SKIP',
  'SERIAL',
  'BIGSERIAL',
  'LVARCHAR',
  'CURRENT',
  'TODAY',
  'MATCHES',
  'UNITS',
  'MODIFY',
  'RENAME COLUMN',
] as const;

const ENGINE_KEYWORDS: Readonly<Record<DatabaseEngine, readonly string[]>> = {
  postgresql: [
    'ILIKE',
    'RETURNING',
    'ON CONFLICT',
    'DO UPDATE',
    'DO NOTHING',
    'OFFSET',
    'LATERAL',
    'ARRAY',
    'JSONB',
    'SERIAL',
    'BIGSERIAL',
    'CURRENT_DATE',
  ],
  sqlserver: [
    'TOP',
    'OFFSET',
    'FETCH NEXT',
    'ROWS ONLY',
    'IDENTITY',
    'NVARCHAR',
    'DATETIMEOFFSET',
    'MERGE',
    'OUTPUT',
    'APPLY',
    'CROSS APPLY',
    'OUTER APPLY',
  ],
  mysql: ['LIMIT', 'OFFSET', 'AUTO_INCREMENT', 'ENGINE', 'ON DUPLICATE KEY UPDATE'],
  informix: INFORMIX_KEYWORDS,
  informixsqli: INFORMIX_KEYWORDS,
  oracle: [
    'DUAL',
    'ROWNUM',
    'ROWID',
    'CONNECT BY',
    'FETCH FIRST',
    'SYSDATE',
    'SYSTIMESTAMP',
    'MERGE INTO',
    'NEXTVAL',
    'GENERATED BY DEFAULT AS IDENTITY',
  ],
  sqlite: [
    'LIMIT',
    'OFFSET',
    'AUTOINCREMENT',
    'ROWID',
    'PRAGMA',
    'ATTACH',
    'ON CONFLICT',
    'DO UPDATE SET',
    'WITHOUT ROWID',
  ],
};

/** Palabras que deben sugerirse para un motor concreto. */
export function keywordsFor(engine: DatabaseEngine): readonly string[] {
  return [...COMMON_KEYWORDS, ...ENGINE_KEYWORDS[engine]];
}

/**
 * Funciones que existen en un motor.
 *
 * Salen del catálogo documentado y no de una lista aparte: así cada función que
 * se sugiere tiene su explicación, y ninguna aparece en un motor que no la
 * conoce —como `LENGTH` en SQL Server, que allí se llama `LEN`—.
 */
export function functionsFor(engine: DatabaseEngine): readonly string[] {
  return functionReferences(engine).map((entry) => entry.name);
}
