<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Druse.Application\Druse.Application.csproj" />
    <ProjectReference Include="..\..\src\Druse.Domain\Druse.Domain.csproj" />
    <ProjectReference Include="..\..\src\Druse.Database.Abstractions\Druse.Database.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Druse.Platform.Native\Druse.Platform.Native.csproj" />
    <ProjectReference Include="..\..\src\Druse.Persistence.Sqlite\Druse.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Druse.Infrastructure\Druse.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Druse.Provider.SqlServer\Druse.Provider.SqlServer.csproj" />
    <ProjectReference Include="..\..\src\Druse.Provider.PostgreSql\Druse.Provider.PostgreSql.csproj" />
    <ProjectReference Include="..\..\src\Druse.Provider.MySql\Druse.Provider.MySql.csproj" />
    <ProjectReference Include="..\..\src\Druse.Provider.Informix\Druse.Provider.Informix.csproj" />
  </ItemGroup>

</Project>