using Druse.Database.Abstractions;
using Druse.Domain;
using Druse.Provider.MySql;
using Druse.Provider.PostgreSql;
using Druse.Provider.SqlServer;

namespace Druse.UnitTests;

/// <summary>
/// El DDL que se escribe para cada motor.
///
/// Se comprueba el texto generado y no su ejecución: lo que distingue a un motor
/// de otro es exactamente esto —cómo cita, cómo declara una identidad y cómo
/// escribe cada `ALTER`—, y es lo que el usuario va a leer antes de confirmar.
/// </summary>
public sealed class TableDesignerTests
{
    private static TableDefinition Pedidos() => new()
    {
        Schema = "ventas",
        Name = "pedidos",
        Columns =
        [
            new TableColumnDefinition
            {
                Name = "id",
                DataType = "INT",
                IsNullable = false,
                IsPrimaryKey = true,
                IsIdentity = true,
            },
            new TableColumnDefinition
            {
                Name = "total",
                DataType = "DECIMAL(12,2)",
                IsNullable = false,
                DefaultValue = "0",
            },
            new TableColumnDefinition { Name = "creado_en", DataType = "DATE" },
        ],
    };

    private static TableAlteration Cambios() => new()
    {
        Table = new DatabaseObject
        {
            Id = "t1",
            Name = "pedidos",
            Kind = DatabaseObjectKind.Table,
            Schema = "ventas",
        },
        AddedColumns =
        [
            new TableColumnDefinition { Name = "nota", DataType = "TEXT" },
        ],
        AlteredColumns =
        [
            new ColumnAlteration
            {
                CurrentName = "total",
                Column = new TableColumnDefinition
                {
                    Name = "importe",
                    DataType = "DECIMAL(14,2)",
                    IsNullable = false,
                },
            },
        ],
        DroppedColumns = ["creado_en"],
    };

    [Fact]
    public void SqlServerEscribeCorchetesEIdentidad()
    {
        var sql = string.Join("\n", new SqlServerTableDesigner().DescribeCreate(Pedidos()));

        Assert.Contains("CREATE TABLE [ventas].[pedidos]", sql, StringComparison.Ordinal);
        Assert.Contains("[id] INT IDENTITY(1,1) NOT NULL", sql, StringComparison.Ordinal);
        Assert.Contains("[total] DECIMAL(12,2) DEFAULT 0 NOT NULL", sql, StringComparison.Ordinal);
        Assert.Contains("[creado_en] DATE NULL", sql, StringComparison.Ordinal);
        Assert.Contains("PRIMARY KEY ([id])", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void PostgreSqlEscribeComillasDoblesEIdentidadEstandar()
    {
        var sql = string.Join("\n", new PostgreSqlTableDesigner().DescribeCreate(Pedidos()));

        Assert.Contains("CREATE TABLE \"ventas\".\"pedidos\"", sql, StringComparison.Ordinal);
        Assert.Contains("GENERATED BY DEFAULT AS IDENTITY", sql, StringComparison.Ordinal);
        Assert.Contains("PRIMARY KEY (\"id\")", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void MySqlEscribeAcentosGravesYAutoIncrement()
    {
        var sql = string.Join("\n", new MySqlTableDesigner().DescribeCreate(Pedidos()));

        // En MySQL el esquema es la base, así que solo hay un nivel que calificar.
        Assert.Contains("CREATE TABLE `ventas`.`pedidos`", sql, StringComparison.Ordinal);
        Assert.Contains("`id` INT AUTO_INCREMENT NOT NULL", sql, StringComparison.Ordinal);
        Assert.DoesNotContain("IDENTITY", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void UnNombreConElCierreDelIdentificadorNoEscapa()
    {
        var table = Pedidos() with { Name = "pedidos]; DROP TABLE clientes; --" };

        var sql = string.Join("\n", new SqlServerTableDesigner().DescribeCreate(table));

        // El corchete de cierre se duplica, así que el nombre entero sigue siendo
        // un identificador y no cierra nada.
        Assert.Contains("[pedidos]]; DROP TABLE clientes; --]", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void LasComillasDeCadaMotorSeDuplican()
    {
        var conComilla = new TableColumnDefinition { Name = "a\"b`c]d", DataType = "TEXT" };
        var table = Pedidos() with { Columns = [conComilla] };

        Assert.Contains(
            "\"a\"\"b`c]d\"",
            string.Join("\n", new PostgreSqlTableDesigner().DescribeCreate(table)),
            StringComparison.Ordinal);

        Assert.Contains(
            "`a\"b``c]d`",
            string.Join("\n", new MySqlTableDesigner().DescribeCreate(table)),
            StringComparison.Ordinal);

        Assert.Contains(
            "[a\"b`c]]d]",
            string.Join("\n", new SqlServerTableDesigner().DescribeCreate(table)),
            StringComparison.Ordinal);
    }

    [Fact]
    public void ElOrdenDeLosCambiosDejaElBorradoParaElFinal()
    {
        var statements = new PostgreSqlTableDesigner().DescribeAlter(Cambios());

        var added = statements.ToList().FindIndex(sql => sql.Contains("ADD", StringComparison.Ordinal));
        var dropped = statements.ToList().FindIndex(sql => sql.Contains("DROP COLUMN", StringComparison.Ordinal));

        // Borrar primero dejaría al resto de instrucciones apuntando a columnas
        // que ya no existen.
        Assert.True(added < dropped);
    }

    [Fact]
    public void PostgreSqlPartCadaCambioDeColumnaEnSuPropiaAccion()
    {
        var sql = string.Join("\n", new PostgreSqlTableDesigner().DescribeAlter(Cambios()));

        Assert.Contains("RENAME COLUMN \"total\" TO \"importe\"", sql, StringComparison.Ordinal);
        Assert.Contains("ALTER COLUMN \"importe\" TYPE DECIMAL(14,2)", sql, StringComparison.Ordinal);
        Assert.Contains("ALTER COLUMN \"importe\" SET NOT NULL", sql, StringComparison.Ordinal);
        Assert.Contains("DROP COLUMN \"creado_en\"", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void MySqlReescribeLaColumnaEnteraAlCambiarla()
    {
        var sql = string.Join("\n", new MySqlTableDesigner().DescribeAlter(Cambios()));

        // `CHANGE` es el único que renombra, y arrastra la definición completa
        // porque lo que no se repita se pierde.
        Assert.Contains(
            "CHANGE `total` `importe` DECIMAL(14,2) NOT NULL",
            sql,
            StringComparison.Ordinal);
    }

    [Fact]
    public void SqlServerRenombraConElProcedimientoDelSistema()
    {
        var sql = string.Join("\n", new SqlServerTableDesigner().DescribeAlter(Cambios()));

        Assert.Contains("sp_rename '[ventas].[pedidos].[total]', 'importe', 'COLUMN'", sql, StringComparison.Ordinal);
        Assert.Contains("ALTER COLUMN [importe] DECIMAL(14,2) NOT NULL", sql, StringComparison.Ordinal);
    }

    [Fact]
    public void RenombrarLaTablaSeHaceAlFinal()
    {
        var alteration = Cambios() with { NewName = "pedidos_2026" };

        foreach (ITableDesigner designer in new ITableDesigner[]
        {
            new SqlServerTableDesigner(),
            new PostgreSqlTableDesigner(),
            new MySqlTableDesigner(),
        })
        {
            var statements = designer.DescribeAlter(alteration);

            // Renombrarla antes dejaría al resto apuntando a un nombre que ya no
            // existe.
            Assert.Contains("pedidos_2026", statements[^1], StringComparison.Ordinal);
        }
    }

    [Fact]
    public void CadaMotorOfreceSusPropiosTipos()
    {
        Assert.Contains("NVARCHAR(255)", new SqlServerTableDesigner().CommonDataTypes);
        Assert.Contains("jsonb", new PostgreSqlTableDesigner().CommonDataTypes);
        Assert.Contains("LONGTEXT", new MySqlTableDesigner().CommonDataTypes);
    }
}
